### ISSUE TITLE
Errors when runing 'example_geo1.m'

### ISSUE THREAD

**Issue by WangMengxiao319** [KIT-IBT/Cobiveco#15]
Hello! 
This is my first time using Cobiveco (on Windows system). After configuring the necessary dependencies according to the installation steps, I opened the cobiveco project in MATLAB and tried to run the **example_geo1.m** project. The following error occurred. Did I make any mistakes? Do I need to download additional data?

![image](https://github.com/user-attachments/assets/cd95da80-8f64-487a-a068-e3186700b175)

I would appreciate your help.

**Comment by Carola-kit** [comment]
Hi,
I had the same issue today and I solved it.
In functions>solveTrajectDist.m in line 98 one "end" is missing. There is only one "end" to close the try and catch and none to close the if in front of it. After I added an "end" in this line, the example worked.

The image shows the code with my correction.

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/1c6f3f8f-268b-4911-8750-043707971a15">

I hope this helps. :)

**Comment by WangMengxiao319** [comment]
> Hi, I had the same issue today and I solved it. In functions>solveTrajectDist.m in line 98 one "end" is missing. There is only one "end" to close the try and catch and none to close the if in front of it. After I added an "end" in this line, the example worked.
> 
> The image shows the code with my correction.
> 
> <img alt="image" width="1091" src="https://private-user-images.githubusercontent.com/66829378/390012673-1c6f3f8f-268b-4911-8750-043707971a15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzMyNTYsIm5iZiI6MTczMjY3Mjk1NiwicGF0aCI6Ii82NjgyOTM3OC8zOTAwMTI2NzMtMWM2ZjNmOGYtMjY4Yi00OTExLTg3NTAtMDQzNzA3OTcxYTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NzhlZGU5NmQ1ZDc4YTkwNTZjMmQ3NTQwMTIyMWUxMWY5ZmMwOWJiZDhhOGE2MWQ3ZjkzYWJjODhmNGM2ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qM5y_h83UW9-Qarsc0sr-8yubLIruFz08_gEsGop6gM">
> I hope this helps.

thanks a lot! It works!

**Comment by axel-loewe** [comment]
Closing with #16
