### ISSUE TITLE
meshio installation not listed in requirements

### ISSUE THREAD

**Issue by jab0707** [KIT-IBT/Cobiveco#8]
meshio (https://github.com/nschloe/meshio) is needed for some parts of createBoundarySurfacesAB.m to function. It should be installed in the base conda environment but it is not included in the requirements.txt

**Comment by axel-loewe** [comment]
Thanks for the feedback @jab0707!
Closed with https://github.com/KIT-IBT/Cobiveco/commit/c2c9fd6dfedfdfbdcf6f6b0c4de85ea261fd948b
